// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var s;
    s = io.connect('http://localhost:3000');
    console.dir(s)
    s.on('connect', function() {});
    s.on('disconnect', function() {});
    s.on('room', function(data) { console.log(data); });
  });

}).call(this);
